import styles from "../styles/Layout.module.css"
import React from "react";
import { viga, gothica1 } from "../styles/fonts";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// design place
function HeaderRectangle() {
    const mockupmenu = {

      width: '100%',
      height: '5rem',
      backgroundColor: '#101118'
     }
  return (<div style={mockupmenu}>
    <p className={styles.mockupmenutext}>
      Recycling | Facts | Infografik | Kontakt
    </p>
  </div>)
}

function Footer() {
  return (
      <div className={styles.footer}>
        <div className={styles.footerContent}>
            Datenschutz
        </div>
        <div className={styles.footerContent}>
            Impressum
        </div>
        <div className={styles.footerContent}>
            Kontakt
        </div>
      </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
    <body className={styles.body}>
        <HeaderRectangle></HeaderRectangle>
        {children}
        <Footer></Footer>
    </body>
    </html>
  )
}
